### ISSUE TITLE
Fix hcard parsing from hubzilla

### ISSUE THREAD

**Issue by jaywink** [jaywink/social-federation#39]
For example, nickname in diaspora hcard is found with selector `dl.entity_nickname span.nickname`. Hubzilla uses an `a` instead of `span`. Could be other differences, loosen up the selectors as far as possible.

**Comment by redmatrix** [comment]
Should be fixed in the latest Hubzilla dev (1.11). There is a potential conflict with Friendica in the use of the hcard public key however. Friendica uses the same field class name but stores a PKCS#8 public key ('BEGIN PUBLIC KEY') which is DFRN protocol compatible and Diaspora stores a PKCS#1 public key ('BEGIN RSA PUBLIC KEY').  

@annando ?

**Comment by annando** [comment]
AFAIK the key in the hcard should be compatible with Diaspora, even with the new Diaspora implementation.

BTW: Please keep in mind that Diaspora moved some stuff (afaik the guid and the public key) from the webfinger to the hcard.

**Comment by jaywink** [comment]
Thanks. Loosened up the selectors anyway to match upcoming  [diaspora docs](http://diaspora.github.io/diaspora_federation/discovery/hcard.html).

@SuperTux88 - I noticed the docs don't list `.nickname` that currently contains the username part of the handle or `.url` which currently contains a link to the server.

Are you dropping these from the hcard or are the docs just missing them currently? It sounds logical to me to be able to parse the full diaspora handle from the hcard itself, and that is what I am currently doing.

**Comment by SuperTux88** [comment]
The documentation lists only the mandatory fields which are used by the protocol. Everyone is free to add other data according to the hcard documentation. `.nickname` and `.url` are not used by the latest diaspora release (but they are probably still needed by older versions). `.url` will probably be replaced by a link to the persons profile in the future.

Why do you parse the diaspora\* ID from the hcard? You need the diaspora\* ID to find the hcard, so it's weird to parse it then again from the hcard if you already have it.

**Comment by jaywink** [comment]
@SuperTux88 I only checked diaspora-fr.org which runs post 0.6 develop and the url and nickname are still there. If they are being dropped, I'll drop them from Social-Federation too.

> You need the diaspora* ID to find the hcard, so it's weird to parse it then again from the hcard if you already have it.

That's actually not true. You need the guid to fetch the hcard. A method that purely fetches a hcard using the guid has no information on the diaspora handle. It seems odd to have to pass the information along through *whose* hcard it is from the method that was used to *find* the hcard address - which is the webfinger method.

**Comment by jaywink** [comment]
> You need the guid to fetch the hcard.

OK that was stupidly said, hasty comment. It does feel logical though that the hCard would have relevant information with it. But as it's not guaranteed, will drop it from the parser, thanks. 👍
